//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCeibaNetv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterTbl
    {
        public CenterTbl()
        {
            this.ClientsTbls = new HashSet<ClientsTbl>();
        }
    
        public int Id { get; set; }
        public string Center { get; set; }
    
        public virtual ICollection<ClientsTbl> ClientsTbls { get; set; }
    }
}
