//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCeibaNetv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsTbl
    {
        public ClientsTbl()
        {
            this.ProgramClientTbls = new HashSet<ProgramClientTbl>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CenterId { get; set; }
        public string MiddleName1 { get; set; }
        public string MiddleName2 { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual CenterTbl CenterTbl { get; set; }
        public virtual ICollection<ProgramClientTbl> ProgramClientTbls { get; set; }
    }
}
