//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCeibaNetv4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaCeibaDbv4Entities : DbContext
    {
        public LaCeibaDbv4Entities()
            : base("name=LaCeibaDbv4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CenterTbl> CenterTbls { get; set; }
        public virtual DbSet<ClientsTbl> ClientsTbls { get; set; }
        public virtual DbSet<LoansTbl> LoansTbls { get; set; }
        public virtual DbSet<PaymentTbl> PaymentTbls { get; set; }
        public virtual DbSet<ProgramClientTbl> ProgramClientTbls { get; set; }
        public virtual DbSet<ProgramTbl> ProgramTbls { get; set; }
        public virtual DbSet<RoundTbl> RoundTbls { get; set; }
        public virtual DbSet<RepFreq> RepFreq { get; set; }
    }
}
