//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCeibaNetv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoansTbl
    {
        public LoansTbl()
        {
            this.PaymentTbls = new HashSet<PaymentTbl>();
        }
    
        public int Id { get; set; }
        public decimal AmtLoan { get; set; }
        public System.DateTime TransferDate { get; set; }
        public bool Active { get; set; }
        public int RoundId { get; set; }
        public Nullable<int> RepFreqId { get; set; }
        public Nullable<int> Instalments { get; set; }
    
        public virtual RoundTbl RoundTbl { get; set; }
        public virtual ICollection<PaymentTbl> PaymentTbls { get; set; }
        public virtual RepFreq RepFreq { get; set; }
    }
}
