//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCeibaNetv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTbl
    {
        public int Id { get; set; }
        public System.DateTime DatePmtDue { get; set; }
        public Nullable<System.DateTime> DatePmtPaid { get; set; }
        public Nullable<decimal> AmtPaid { get; set; }
        public int LoanId { get; set; }
    
        public virtual LoansTbl LoansTbl { get; set; }
    }
}
