//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCeibaNetv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramClientTbl
    {
        public ProgramClientTbl()
        {
            this.RoundTbls = new HashSet<RoundTbl>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int ProgramId { get; set; }
    
        public virtual ClientsTbl ClientsTbl { get; set; }
        public virtual ProgramTbl ProgramTbl { get; set; }
        public virtual ICollection<RoundTbl> RoundTbls { get; set; }
    }
}
