//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCeibaNetv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramTbl
    {
        public ProgramTbl()
        {
            this.ProgramClientTbls = new HashSet<ProgramClientTbl>();
        }
    
        public int Id { get; set; }
        public string Program { get; set; }
        public double InterestRate { get; set; }
    
        public virtual ICollection<ProgramClientTbl> ProgramClientTbls { get; set; }
    }
}
