//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCeibaNetv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundTbl
    {
        public RoundTbl()
        {
            this.LoansTbls = new HashSet<LoansTbl>();
        }
    
        public int Id { get; set; }
        public int PClientNameId { get; set; }
        public int RoundNum { get; set; }
    
        public virtual ICollection<LoansTbl> LoansTbls { get; set; }
        public virtual ProgramClientTbl ProgramClientTbl { get; set; }
    }
}
